# Generated by Django 3.1.7 on 2021-03-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='colorvariant',
            options={'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Фото Продуктов'},
        ),
        migrations.AlterModelOptions(
            name='quantityvariant',
            options={'verbose_name_plural': 'Количество'},
        ),
        migrations.AlterModelOptions(
            name='sizevariant',
            options={'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
