# Generated by Django 3.1.7 on 2021-02-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='total_price',
        ),
    ]
