# Generated by Django 3.1.7 on 2021-03-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cartitems_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name_plural': 'Товары в Корзине'},
        ),
        migrations.AddField(
            model_name='cartitems',
            name='isOrder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
